### ISSUE TITLE
specific mssage for each shareing type

### ISSUE THREAD

**Issue by syrakozz** [BobDG/BDGShare#1]
hi 
how i can use 
[BDGSharing shareUsingActivityController:@"Text" urlStr:@"Url str" image:nil whatsapp:TRUE];

but with specify the message for each share type ?  like , facebook , , twitter.....

**Comment by BobDG** [comment]
Hi, using the activity controller you currently can't. You can however share to each of these services individually using [BDGSharing shareTwitter, shareFacebook, etc. But you will need to have separate buttons (or an actionsheet) in your App.
