### ISSUE TITLE
view is not in the window hierarchy!

### ISSUE THREAD

**Issue by syrakozz** [BobDG/BDGShare#11]
im getting Warning: Attempt to present <MFMailComposeViewController: 0x7ff4fb09ac00> on <DoActionSheetController: 0x7ff4fd3f55a0> whose view is not in the window hierarchy!
and im not able to share

**Comment by BobDG** [comment]
@syrakozz Perhaps you didn't provide the presentingViewController? The it defaults to the applications rootviewcontroller..

**Comment by syrakozz** [comment]
tx
