### ISSUE TITLE
instagram share

### ISSUE THREAD

**Issue by syrakozz** [BobDG/BDGShare#3]
could you plz add sharing via instagram it will be great

**Comment by sohayb** [comment]
:+1:

**Comment by BobDG** [comment]
I'll look into this!

**Comment by BobDG** [comment]
It seems Instagram does not support direct sharing with an API, you need to use the uidocumentinteractioncontroller. Fortunately, my sharing tool already does support it. Follow this link how to convert your image to the correct .igo format and usy my cocoapod to share it with the uidocumentinteractioncontroller. 

http://stackoverflow.com/questions/11393071/how-to-share-an-image-on-instagram-in-ios

**Comment by syrakozz** [comment]
maybe if you can merge this with it 
https://github.com/coryalder/DMActivityInstagram
it will be great

**Comment by syrakozz** [comment]
and it will be the ultimate project control :)
