### ISSUE TITLE
Warning: Attempt to present <UIActivityViewController: 0x7a64f430> on <UINavigationController: 0x7a71b220> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by syrakozz** [BobDG/BDGShare#4]
Warning: Attempt to present <UIActivityViewController: 0x7a64f430> on <UINavigationController: 0x7a71b220> whose view is not in the window hierarchy!

**Comment by syrakozz** [comment]
if you add this ,
https://github.com/coverback/CVKHierarchySearcher
to this problem it will be much better

**Comment by BobDG** [comment]
Hy Syrakozz,

Probably you tried to show the activitycontroller on a view that's, as the warning says, not in the window hierarchy. Did you try to show it in viewDidLoad or something like that?

**Comment by syrakozz** [comment]
i try to showit in a viewmodelviewcontroller, so i got that error, 
but then i modify the get controller method in your code , and i try to get it using 
https://github.com/coverback/CVKHierarchySearcher

CVKHierarchySearcher *hierarchy = [[CVKHierarchySearcher alloc] init];
UIViewController *topmost = hierarchy.topmostViewController;

and it works fine

**Comment by BobDG** [comment]
Ah you used it without setting the presentingViewController. I'll look into the CVKHierarchySearcher.

**Comment by syrakozz** [comment]
great, thank you
